[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@yearnvaults/=lib/yearn-vaults/',
    '@openzeppelin/=lib/openzeppelin-contracts/'
]
fuzz_runs = 10 

# See more config options https://github.com/gakonst/foundry/tree/master/config
